### ISSUE TITLE
 Soportar varios pokemon

### ISSUE THREAD

**Issue by elicasama** [elicasama/ejercicios-js-nodejs#10]
El sistema debe poder indicar el pokemon con mayor *stat total* indistintamente la cantidad de pokemon a comparar.

**Comment by rodri042** [comment]
Este issue debería llamarse **Soportar varios pokemon** o algo así, no el archivo que tenés que modificar :stuck_out_tongue_winking_eye:

**Comment by elicasama** [comment]
@rodri042, Ahí quedó mejor?

**Comment by rodri042** [comment]
Qué cambiaste además del nombre?

**Comment by rodri042** [comment]
Sep

**Comment by rodri042** [comment]
Sintácamente la descripción no compila xD
