### ISSUE TITLE
Simulación de acceso a la api

### ISSUE THREAD

**Issue by elicasama** [elicasama/ejercicios-js-nodejs#4]
@rodri042  cómo se puede simular el acceso a la api de pokemon, (algo como lo que ya hiciste en su momento en el otro proyecto) y recuperar al menos 2 pokemons?
La idea es no necesitar salir a la web y poder continuar con el ejercicio.

**Comment by rodri042** [comment]
Podés editar el método que busca de la Pokedex para que devuelva el objeto
que vos quieras. Si usás:
`Promise.resolve(objeto)` te devuelve una Promesa que siempre resuelve a
`objeto`.
Usando eso, más metiendo en el código algún JSON de un poke, ya estarías.

Si estás inspirada en vez de `Promise.resolve` usarías `mocha` y `nock`.
Pero no quiero meter más ruido por ahora con otras tecnologías. Los hacés
en una segunda iteración.

**Comment by rodri042** [comment]
Dos cosas más:
- Cuando dije `Promise` hablaba de la biblioteca de promesas `bluebird` que
deberías instalar.
- Sobre los issues: Si te quedan dudas, respondeme, obvio. Cuando esté todo
clarísssssimo, ¡cerrá el issue! :smile:
