### ISSUE TITLE
Help with mocha

### ISSUE THREAD

**Issue by elicasama** [elicasama/ejercicios-js-nodejs#7]
@rodri042 , antes de decir que tengo problemas con el armado de los test, te comento que no puedo ejecutarlos T_T
Instalé mocha, y se puede ver en el archivo package.json que figura la dependencia
  },
  "devDependencies": {
    "chai": "^3.5.0"
  }

luego armé un test y cuando voy a correrlo con *mocha tests --recursive --watch*  o *mocha tests --watch* 
me dice que no encuentra el comando.
*zsh: command not found: mocha*

Qué me está faltanto?

**Comment by rodri042** [comment]
Leer.

En el [tuto que me pasaste ayer](https://www.codementor.io/nodejs/tutorial/unit-testing-nodejs-tdd-mocha-sinon) decía `npm install mocha -g`.

Eso lo va a instalar globalmente para que el comando `mocha` esté disponible en la shell.

**Comment by rodri042** [comment]
Además:

Instalé mocha, y se puede ver en el archivo package.json que figura la dependencia
},
"devDependencies": {
"chai": "^3.5.0"
}

1) Yo no lo veo
2) No debería estar, ya que lo instalás globalmente en el sistema y no en el proyecto
