### ISSUE TITLE
Generar los test para pokemonComparator y pokemon

### ISSUE THREAD

**Issue by elicasama** [elicasama/ejercicios-js-nodejs#8]
Crear los test para las clases pokemon y pokemonComparator.

**Comment by elicasama** [comment]
@rodri042 , podrías ver cómo quedaron?

**Comment by elicasama** [comment]
No se cerró con el comentario en el merge del pull request #9 , por tal motivo lo cierro a mano.

**Comment by rodri042** [comment]
@elicasama No se cerró porque no le pusiste el Fixes #8 como te dije
